const redColorDB = [{
    src:'./images/product/product001.png',
    platform:'구구스',
    brand:'샤넬',
    title:'22백 스몰 AS3260',
    price:8413000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/product002.png',
    platform:'구구스',
    brand:'에르메스',
    title:'H아워 다이아 골드 시계',
    price:7379000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/product003.png',
    platform:'구구스',
    brand:'불가리',
    title:'디바스 드림 귀걸이',
    price:3998000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/product004.png',
    platform:'',
    brand:'피에가',
    title:'ACE50 Wireless TX/RX 액티브 플로팅 스피커',
    price:9720000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/product005.png',
    platform:'',
    brand:'드비알레',
    title:'팬텀1 하이엔드 스피커 108dB (택 1)',
    price:5290000,
    point:100,
    delivery:'무료',
}]
const greenColorDB = [{
    src:'./images/product/g_product001.jpg',
    platform:'',
    brand:'아난티',
    title:'아난티앳부산코드/ 웨이브인아난티 카바나 2인 패키지',
    price:198000,
    point:70,
    delivery:'',
},{
    src:'./images/product/g_product002.jpg',
    platform:'',
    brand:'롯데호텔 서울',
    title:'라세느 주중(월~목) 런치 1인',
    price:173000,
    point:70,
    delivery:'',
},{
    src:'./images/product/g_product003.jpg',
    platform:'',
    brand:'롯데호텔 서울',
    title:'델리카한스 프리미엄 망고 케이크',
    price:115000,
    point:70,
    delivery:'',
},{
    src:'./images/product/g_product004.jpg',
    platform:'',
    brand:'메리어트 본보이',
    title:'JW메리어트제주 / 풀보드 패키지(월~목)',
    price:1485000,
    point:70,
    delivery:'',
},{
    src:'./images/product/g_product005.jpg',
    platform:'',
    brand:'롯데호텔 서울',
    title:'도림 복 코스 1인',
    price:160000,
    point:70,
    delivery:'',
}]
const pinkColorDB = [{
    src:'./images/product/p_product001.jpg',
    platform:'',
    brand:'마르니',
    title:'스몰 자카드 쇼퍼백',
    price:611500,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/p_product002.jpg',
    platform:'',
    brand:'메종마르지엘라',
    title:'x살로몬 XT 15 백팩',
    price:388400,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/p_product003.png',
    platform:'',
    brand:'헌터',
    title:'오리지널 톨 레인 부츠 블랙',
    price:125000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/p_product004.jpg',
    platform:'',
    brand:'플르부아',
    title:'오 드 퍼퓸 50mL (4종 택1)',
    price:64000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/p_product005.jpg',
    platform:'',
    brand:'입생로랑',
    title:'러브샤인 립 듀오 스프링 기프트 세트',
    price:78000,
    point:70,
    delivery:'무료',
}]
const bestProductDB = [{
    num:1,
    src:'./images/product/product006.png',
    brand:'다이슨',
    title:'에어랩 i.d 멀티 스타일러 앤 드라이어',
    price:'',
    salePrice:699000,
    percent:'',
    point:50,
    delivery:'무료',
},{
    num:2,
    src:'./images/product/product007.png',
    brand:'삼성',
    title:'갤럭시 버즈3 프로 택1',
    price:319000,
    salePrice:232870,
    percent:27,
    point:50,
    delivery:'무료',
},{
    num:3,
    src:'./images/product/product008.png',
    brand:'다이슨',
    title:'슈퍼소닉 헤어드라이어 (택1)',
    price:'',
    salePrice:479000,
    percent:'',
    point:50,
    delivery:'무료',
},{
    num:4,
    src:'./images/product/product009.png',
    brand:'한일',
    title:'아기바람 저소음 리모컨식 선풍기',
    price:85000,
    salePrice:80700,
    percent:5,
    point:100,
    delivery:'무료',
},{
    num:5,
    src:'./images/product/product010.png',
    brand:'DJI',
    title:'오즈모 포켓3 외 (택1)',
    price:'',
    salePrice:726000,
    percent:'',
    point:50,
    delivery:'무료',
}]
const artProductDB = [{
    src:'./images/product/art_product001.png',
    brand:'아투',
    title:'Heejoon Lee - Utopia',
    price:800000,
},{
    src:'./images/product/art_product002.png',
    brand:'아투',
    title:'Lee Ufan - Untitled (IV)',
    price:12000000,
},{
    src:'./images/product/art_product003.png',
    brand:'아투',
    title:'Jeroz - Driver',
    price:1500000,
}]
const weekBestProductDB = [{
    src:'./images/product/product011.png',
    brand:'무아스',
    reviewnum:4.6,
    title:'루프 욕실시계',
    price:14800,
},{
    src:'./images/product/product012.png',
    brand:'킨토',
    reviewnum:3.3,
    title:'알프레스코 플레이트 250mm',
    price:20000,
},{
    src:'./images/product/product013.png',
    brand:'에스티로더',
    reviewnum:4.8,
    title:'더블웨어 파운데이션_30ml',
    price:91000,
},{
    src:'./images/product/product014.png',
    brand:'몽슈레',
    reviewnum:4.8,
    title:'태열배게',
    price:84600,
},{
    src:'./images/product/product015.png',
    brand:'발뮤다',
    reviewnum:4.7,
    title:'더 토스터 5cc마그넷컵',
    price:20000,
}]
const reviewItemDB = [{
    src:'./images/product/product016.png',
    brand:'한일',
    title:'아기바람 저소음 리모컨식 선풍기',
    percent:5,
    price:80700,
    text:'2025년 생산제품이라 좋구요... m포인트에 선풍기가 많아 이것저것 찾아보다 아기바람 기능이 있어서 수면할때 좋겠구나 생각하고 구매했는데... 현명한 선택이었네요.. 수면할때 조용하고 너무 좋아요 화이트라 제품깔끔하고 깨끗하게 생겼어요... 잘 구매했어요 추가구매할게요',
    id:'min********',
},{
    src:'./images/product/product017.png',
    brand:'오드앵글',
    title:'1등급 18L 제습기',
    percent:'',
    price:289000,
    text:'성능 좋아요 배송 주말 포함 4일 걸렸어요<br>금요일 주문 - 월요일 발송 - 화요일도착<br>33평 거실에 두었는데 거실 주방까지 잘 커버되는거같아요(거실 주방 습도 같이 떨어지고 차이는 3-4프로) 80프로에서 시작해서 50프로대까지 떨어지는데 한시간반정도 걸리는거 같아요 이제 여름이 길어지고 장마기간이 우기라고 쳐도 될 법하게 길어져서 하나 더 사야하나 고민중입니다<br>-소음수준 : 선풍기 틀어놓은 정도-',
    id:'pul******',
},{
    src:'./images/product/product018.png',
    brand:'엑사이더',
    title:'하이엔드 러닝바이크 실내자전거',
    percent:'',
    price:239000,
    text:'익이 이제품에 대해선 소문을 들었구요,<br>10분 이상 안쉬고 타기 쉽지 않다고 했는데, 주 2회 필라 1:1 + 주2회 피티1:1하는 닝겐인데여, 10분이 뭐에여...<br>저 2분 경우 타고 내려왔구요,<br>안쉬고 10분 타시는 분들 존경!!!<br>허리가 아픈 사람이라 서서타는게 좋다고 해서 산건대 진짜 완전 코어 제대로 잡아주구요, 대신 무릎 아프신 분들은 조심해서 타셔야 합니다.<br>그리고 코어에 힘을 주고 타셔야해요~<br>무릎으로만 구르고 타시면 앙대요~',
    id:'rai*****',
},{
    src:'./images/product/product019.png',
    brand:'말본골프',
    title:'더블 아트웍 라운드 티셔츠',
    percent:'',
    price:159000,
    text:'입는 순간 느낌 부드럽고 느낌이 너무 좋네용<br>다른 티들 보면 사이즈 크개 사면 목부분도 커져서 늘어져 보이는데 이건 그렇지 않아 좋습니다.<br>같이 구매한 다른 티셔츠는 XL인데 이 티셔츠 XXL가 목부분은 조금 더 타이트 하네요 2만원 비싸다고 재질은 느낌은 더 좋네요~ 암튼 너무너무 맘에 듭니다.',
    id:'mcj*****',
}]