const redColorDB = [{
    src:'./images/product/product001.png',
    platform:'구구스',
    brand:'샤넬',
    title:'22백 스몰 AS3260',
    price:8413000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/product002.png',
    platform:'구구스',
    brand:'에르메스',
    title:'H아워 다이아 골드 시계',
    price:7379000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/product003.png',
    platform:'구구스',
    brand:'불가리',
    title:'디바스 드림 귀걸이',
    price:3998000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/product004.png',
    platform:'',
    brand:'피에가',
    title:'ACE50 Wireless TX/RX 액티브 플로팅 스피커',
    price:9720000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/product005.png',
    platform:'',
    brand:'드비알레',
    title:'팬텀1 하이엔드 스피커 108dB (택 1)',
    price:5290000,
    point:100,
    delivery:'무료',
}]
const greenColorDB = [{
    src:'./images/product/g_product001.jpg',
    platform:'',
    brand:'아난티',
    title:'아난티앳부산코드/ 웨이브인아난티 카바나 2인 패키지',
    price:198000,
    point:70,
    delivery:'',
},{
    src:'./images/product/g_product002.jpg',
    platform:'',
    brand:'롯데호텔 서울',
    title:'라세느 주중(월~목) 런치 1인',
    price:173000,
    point:70,
    delivery:'',
},{
    src:'./images/product/g_product003.jpg',
    platform:'',
    brand:'롯데호텔 서울',
    title:'델리카한스 프리미엄 망고 케이크',
    price:115000,
    point:70,
    delivery:'',
},{
    src:'./images/product/g_product004.jpg',
    platform:'',
    brand:'메리어트 본보이',
    title:'JW메리어트제주 / 풀보드 패키지(월~목)',
    price:1485000,
    point:70,
    delivery:'',
},{
    src:'./images/product/g_product005.jpg',
    platform:'',
    brand:'롯데호텔 서울',
    title:'도림 복 코스 1인',
    price:160000,
    point:70,
    delivery:'',
}]
const pinkColorDB = [{
    src:'./images/product/p_product001.jpg',
    platform:'',
    brand:'마르니',
    title:'스몰 자카드 쇼퍼백',
    price:611500,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/p_product002.jpg',
    platform:'',
    brand:'메종마르지엘라',
    title:'x살로몬 XT 15 백팩',
    price:388400,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/p_product003.png',
    platform:'',
    brand:'헌터',
    title:'오리지널 톨 레인 부츠 블랙',
    price:125000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/p_product004.jpg',
    platform:'',
    brand:'플르부아',
    title:'오 드 퍼퓸 50mL (4종 택1)',
    price:64000,
    point:100,
    delivery:'무료',
},{
    src:'./images/product/p_product005.jpg',
    platform:'',
    brand:'입생로랑',
    title:'러브샤인 립 듀오 스프링 기프트 세트',
    price:78000,
    point:70,
    delivery:'무료',
}]